name: Keep Render Service Alive

# Déclencheur : toutes les 13 minutes (checker la limite de github)
on:
  schedule:
    - cron: '*/13 * * * *'
  
  # Permet aussi de déclencher manuellement
  workflow_dispatch:

jobs:
  ping-service:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Ping backend service
        run: |
          echo "Pinging service at $(date)..."
          
          # Tentative avec timeout de 30 secondes
          response=$(curl -s -o /dev/null -w "%{http_code}" --max-time 30 https://site-web-perso-cjp2.onrender.com/ping)
          
          if [ $response -eq 200 ]; then
            echo "✅ Service is alive (HTTP $response)"
          else
            echo "❌ Service returned HTTP $response"
            echo "Retrying in 30 seconds..."
            sleep 30
            
            # Deuxième tentative
            response=$(curl -s -o /dev/null -w "%{http_code}" --max-time 30 https://site-web-perso-cjp2.onrender.com/ping)
            
            if [ $response -eq 200 ]; then
              echo "✅ Service recovered (HTTP $response)"
            else
              echo "❌ Service still down (HTTP $response)"
              exit 1
            fi
          fi
      
      - name: Log timestamp
        run: echo "Last ping at $(date)"